### ISSUE TITLE
Error in edit.setup(data, setup, ...) : nothing left to impute

### ISSUE THREAD

**Issue by englianhu** [stefvanbuuren/mice#146] opened 2018-10-11 12:28 UTC
```r
> Y2015W1_tm1_NA
# A tibble: 7,216 x 9
   index               BidOpen BidHigh BidLow BidClose AskOpen AskHigh AskLow AskClose
   <dttm>                <dbl>   <dbl>  <dbl>    <dbl>   <dbl>   <dbl>  <dbl>    <dbl>
 1 2015-01-04 22:01:00    120.    121.   120.     121.    121.    121.   121.     121.
 2 2015-01-04 22:02:00    121.    121.   120.     121.    121.    121.   121.     121.
 3 2015-01-04 22:03:00    121.    121.   121.     121.    121.    121.   121.     121.
 4 2015-01-04 22:04:00    121.    121.   121.     121.    121.    121.   121.     121.
 5 2015-01-04 22:05:00    121.    121.   120.     121.    121.    121.   121.     121.
 6 2015-01-04 22:06:00     NA     121.   120.     120.    121.    121.   121.     121.
 7 2015-01-04 22:07:00    120.    121.   120.     121.    121.    121.   120.     121.
 8 2015-01-04 22:08:00    121.    121.   121.     121.    121.    121.   121.     121.
 9 2015-01-04 22:09:00    121.    121.   121.     121.    121.    121.   121.     121.
10 2015-01-04 22:10:00    121.    121.   121.     121.    121.    121.   121.     121.
# ... with 7,206 more rows
> mice(Y2015W1_tm1_NA[,-1])
Error in edit.setup(data, setup, ...) : nothing left to impute
```

**Comment by stefvanbuuren** [comment] 2018-10-16 10:56
Closing this because it's expected behaviour.

**Closed by stefvanbuuren** 2018-10-16 10:56 UTC

**Comment by heuristicwondering** [comment] 2019-01-10 18:00
@stefvanbuuren can you explain why this is expected behavior since there is an NA in the "BidOpen" column? Why is this value not imputed? I'm trying to understand how the mice function works but not sure I quite get it yet.

**Comment by stefvanbuuren** [comment] 2019-01-11 07:13
That's because `[,-1]` dropped `BidOpen`

**Comment by squalo78** [comment] 2019-09-25 09:51
@stefvanbuuren, I am not sure it is correct what you are saying. Because [,-1] should drop the 'index' variable and not 'Bidopen'. 
'index' is indeed the first variable (it is not row names).

I am commenting this now because I get a similar error as in this post and it is not obvious why this is the case (as my dataframe has 'missing' entries)

**Comment by stefvanbuuren** [comment] 2019-09-25 13:25
Version 3.6.2 has a more informative error message. See also #194
