### ISSUE TITLE
rbind(mids, not-mids) and complete()

### ISSUE THREAD

**Issue by stephematician** [stefvanbuuren/mice#59] opened 2017-12-01 03:32 UTC
The `rbind()` function seems to incorrectly record the `where` component when the second argument is not a mids object. Here's a fairly small working example: 

I make a small `data.frame` which has some missing values in the first column. I take the first five rows and impute missing data using these rows only. I then take the last five rows of the original `data.frame`, `rbind` them to the mids object, and call `complete()`. Comparing the output of complete to the original data, I see that some of the data in the last five rows have been spuriously replaced.

    x <- rnorm(10)
    D <- data.frame(x=x, y=2*x+rnorm(10))
    D[2:4, 1] <- NA
    D

                x          y
    1  -0.5022894 -0.6508769
    2          NA -3.6318003
    3          NA  1.5217955
    4          NA -0.3743209
    5  -0.8211472 -2.2264775
    6  -1.2333469 -2.8954239
    7   1.1697205  2.9399150
    8   0.3635420  1.2758400
    9   0.1315395 -0.1022368
    10 -1.4950373 -2.6565171

    D_mids <- mice(D[1:5,])
    D_rbind <- mice:::rbind.mids(D_mids, D[6:10,])

    complete(D_rbind, 1)
                x          y
    1  -0.5022894 -0.6508769
    2  -0.5022894 -3.6318003
    3  -0.8211472  1.5217955
    4  -0.8211472 -0.3743209
    5  -0.8211472 -2.2264775
    6  -1.2333469 -2.8954239
    7  -0.5022894  2.9399150
    8  -0.8211472  1.2758400
    9  -0.8211472 -0.1022368
    10 -1.4950373 -2.6565171

    D
                x          y
    1  -0.5022894 -0.6508769
    2          NA -3.6318003
    3          NA  1.5217955
    4          NA -0.3743209
    5  -0.8211472 -2.2264775
    6  -1.2333469 -2.8954239
    7   1.1697205  2.9399150
    8   0.3635420  1.2758400
    9   0.1315395 -0.1022368
    10 -1.4950373 -2.6565171

Upon debugging - it seems that the source of the problem is that `where` is not adjusted to the new size of the data.

    > mice:::rbind.mids
    function (x, y = NULL, ...) 
    {
        call <- match.call()
        if (!is.mids(y)) {
            ...
            data <- rbind(x$data, y)
            where <- x$where
            ...
        } ...
    }

**Comment by stephematician** [comment] 2017-12-01 04:33
I think revising the assignment to where in rbind.mids above to:

    where <- rbind(x$where, is.na(y))

would suffice to fix this issue

**Comment by squalo78** [comment] 2017-12-06 10:42
I had a similar issue. 
I think the issue is that:
> print(dim(D_rbind$data))
[1] 10  2
> print(dim(D_rbind$where))
[1] 5 2

But I disagree with the solution you are proposing. I would instead suggest something like 

where <- rbind(x$where, matrix(FALSE, ncol=ncol(y), nrow=nrow(y)) )

The reason being that when we use rbind.mids, I think the object 'y' should be left untouched (also the missing in y)

**Comment by squalo78** [comment] 2017-12-06 10:46
What I wanted to say is that the dimensions of D_rbind$data and D_rbind$where are not consistent. I think this is what is causing issues then with the mice:::complete() function.

**Comment by stephematician** [comment] 2017-12-06 10:50
I don't mind either way, I assumed that the `where` variable was supposed to indicate where missing data is located in the dataset, hence my proposal. Note that the assignment to `imp` in the `rbind.mids` function already ensures that no imputation is performed on the `y` dataset regardless of the value of `where`.

And yep, I agree regarding your reasoning for the misbehaviour in `complete()`.

**Comment by squalo78** [comment] 2017-12-06 13:05
I think the the 'where' determine how 'complete' will fills the missing.

If you run the code below, then the issue you describe is solved.

x <- rnorm(10)
D <- data.frame(x=x, y=2*x+rnorm(10))
D[2:4, 1] <- NA

D_mids <- mice(D[1:5,])

y <- D[6:10,]
D_rbind <- mice:::rbind.mids(x=D_mids, y=y)
D_rbind$where <- rbind(D_rbind$where, matrix(FALSE, ncol=ncol(y), nrow=nrow(y)) )

mice:::complete(D_rbind, 1, include=T)
print(D)

One issue which I still have is that if I introduce some NAs in the 'y' data, it fails:

x <- rnorm(10)
D <- data.frame(x=x, y=2*x+rnorm(10))
D[2:4, 1] <- NA

D_mids <- mice(D[1:5,])

y <- D[6:10,]
y[4:5,1] <- NA
D_rbind <- mice:::rbind.mids(x=D_mids, y=y)
D_rbind$where <- rbind(D_rbind$where, matrix(FALSE, ncol=ncol(y), nrow=nrow(y)) )

mice:::complete(D_rbind, 1, include=T)

with the error below:
Error in `[<-.data.frame`(`*tmp*`, where[, j], j, value = c(0.700183624923754,  : 
  replacement has 5 rows, data has 3

**Comment by stephematician** [comment] 2017-12-06 13:20
Using `is.na(y)` in assignment to `where` will work in both cases you describe, without error.

**Comment by stefvanbuuren** [comment] 2017-12-06 21:21
Thanks. Just pushed a fix for this.

**Closed by stefvanbuuren** 2017-12-06 21:21 UTC

**Comment by stephematician** [comment] 2017-12-07 00:04
All good, I get why `where=F` assignment is the correct approach. Just FYI - this means that in `rbind.mids()` the following code

       # The original data of y will be copied into the multiple imputed dataset, including the missing values of y.
        r <- !wy
        imp <- vector("list", ncol(y))
        for (j in visitSequence) {
          imp[[j]] <- 
            rbind(x$imp[[j]], 
                  as.data.frame(matrix(NA, nrow = sum(!r[, j]), ncol = x$m, 
                                       dimnames = list(row.names(y)[r[, j] == FALSE], 1:m))))
        }
        names(imp) <- varnames

can be replaced with

    imp <- x$imp

**Comment by stefvanbuuren** [comment] 2017-12-08 16:31
Thanks. Great simplification.
