### ISSUE TITLE
Using polyreg or polr functions

### ISSUE THREAD

**Issue by rgutman** [stefvanbuuren/mice#111] opened 2018-06-26 17:48 UTC
Hi,

I am using the latest version of MICE, and I am trying to use the polyreg and polr imputations. I received the error that there are "too many (2163) weights", so I followed the suggestions online and inserted nnet.MaxNWts=1500 to mice. This didn't change anything. I then followed with just MaxNWts, but this returned an error "argument "MaxNWts" matched by multiple actual arguments". So I tried using the cart imputation instead, this time everything worked, the only problem is that CART imputed NA for some of the values. So I am at a loss here.

Thanks,

Roee

**Comment by gerkovink** [comment] 2018-06-26 17:59
Dear Roee,

I do not know the specifics about your data and missinnness problem, but I suspect that at least one of the factors in your imputation model has many levels. Setting the predictorMatrix to exclude such variables as a predictor for some, or all incomplete variables may solve the problem. 

To help you with the NA imputations for cart, I would need more detail.

All the best,

Gerko

**Comment by rgutman** [comment] 2018-06-26 18:15
Hi Gerko,

Thank you for the quick response. Yes there two variables with 7 and 8 values. I can exclude them. The CART imputation simply left these values as NAs. It is almost as if the NAs are treated as a plausible level.

Roee

**Comment by gerkovink** [comment] 2018-06-26 18:44
Does the loggedEvents say anything about these variables being excluded? Another option is when the NAs are hardcoded as categories. The algorithm would then see the category as a valid imputable level.

**Comment by stefvanbuuren** [comment] 2018-06-27 07:21
Roee, thanks. You write:

_.. but this returned an error "argument "MaxNWts" matched by multiple actual arguments"._ 

This sounds like an old programming error that I thought was already long gone. But perhaps it resurfaced. I'll check.

**Comment by stefvanbuuren** [comment] 2018-06-27 07:34
In order to prevent name clashes as you reported, we changed names of these arguments to `nnet.MaxNWts`, `nnet.maxit` and `nnet.trace`. Could you try these?

**Comment by rgutman** [comment] 2018-06-27 14:50
I have actually tried using the nnet.MaxNWts and nnet.trace and it seemed
to have no effect. I found my problem with working with CART it seems that
when there is collinearity CART does not produce any proposals, while pmm
does. So if I remove certain variables CART is working. This is just
inconsistency in the results produced.

**Comment by gerkovink** [comment] 2018-06-27 15:15
`mice.impute.pmm` automatically falls back to ridge regression when computational problems arise with respect to the parameter estimation.  `mice.impute.cart` does not build on the same estimation device and therefore does not have this behaviour. It seems that the interaction of variables causes issues with respect to the number of levels that have to be estimated. 

Raising `net.MaxNWts` till the problem disappears may be a fix, but can be a rather lengthy one. The authors of the `nnet` package mention 

> There is no intrinsic limit in the code, but increasing MaxNWts will probably allow fits that are very slow and time-consuming.

`mice.impute.polr` and `mice.impute.polyreg` use `nnet::multinomial()` for parameter estimation.  So instead of arbitrarily raising `nnet.MaxNWts` it may indeed be more efficient to exclude the culprits from from predicting any other variables in the algorithm by setting a custom `predictorMatrix`.

**Comment by gerkovink** [comment] 2018-06-27 15:18
Since this issue (#111) seems to be related to your data and the resulting estimation problem, and not in particular to any problems with the code in `mice`, I propose that we close this issue. 

@rgutman Would you agree?

**Comment by rgutman** [comment] 2018-06-27 15:28
Yes.  This is totally fine to close it.

Thank you for your help.

Best,

Roee

**Comment by gerkovink** [comment] 2018-06-27 15:29
Cool

**Closed by gerkovink** 2018-06-27 15:29 UTC
